version: '3'

services:
  ray_head:
    build:
      context: ./head
      dockerfile: Dockerfile
    container_name: ray_head
    environment:
      - JUPYTER_ENABLE_LAB=yes
    shm_size: 2gb
    ports:
      - "8888:8888"
      - "6379:6379"
      - "8265:8265"
      - "9090:9090"
      # - "3000:3000"
    volumes:
      - ray_data:/tmp/ray

  ray_worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - ray_head
    command: >
      /bin/bash -c "RAY_USE_MULTIPROCESSING_CPU_COUNT=1 ray start --address=ray_head:6379 && tail -f /dev/null"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - RAY_USE_MULTIPROCESSING_CPU_COUNT=1
    shm_size: 2gb
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: '2g'

  ray_grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - ray_head
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./head/metrics/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

volumes:
  ray_data:
  grafana_data: