global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'jupyterhub'
    metrics_path: '/hub/metrics'
    static_configs:
      - targets: ['10.10.1.10:10003']

  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['127.0.0.1:9100']

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['127.0.0.1:8080']